### ISSUE TITLE
Strings not being parsed from config file?

### ISSUE THREAD

**Issue by unilock** [sisby-folk/kaleido-config#2] opened 2024-01-31 19:27 UTC
It seems that config class fields of type `String` aren't parsed with the rest of the config file; rather, they're always read as their default value.

To reproduce, create the following config class:

```java
public class ExampleConfig extends WrappedConfig {
    @Comment("This is an example configurable String.")
    public final String exampleString = "example_value";

    @Comment("This is an example configurable boolean.")
    public final boolean exampleBoolean = true;
}
```

With the following main class to test it:

```java
public class Main {
    public static final ExampleConfig CONFIG = ExampleConfig.createToml(Paths.get("").toAbsolutePath(), "config", "example", ExampleConfig.class)

    public static void main(String[] args) {
        System.out.println("exampleString: " + CONFIG.exampleString);
        System.out.println("exampleBoolean: " + CONFIG.exampleBoolean);
    }
}
```

When run the first time, the above code will print:

```
exampleString: example_value
exampleBoolean: true
```

Then edit the generated config file manually as such:

```toml
# This is an example configurable String.
# default: example_value
exampleString = "new_value"

# This is an example configurable boolean.
# default: true
exampleBoolean = false
```

(so, change `exampleString` to `"new_value"`, and `exampleBoolean` to `false`)

Finally, run the code again. It will print the following:

```
exampleString: example_value
exampleBoolean: false
```

`exampleString` is still read as its default value, while `exampleBoolean` is read as its updated value from the config file.

Maybe I'm doing something wrong...?

**Comment by sisby-folk** [comment] 2024-01-31 22:56
You should be always using final objects - so `Boolean`, not `boolean`. Not sure why string isnt' working, but I've definitely used it before, so check that first and then get back to us.

**Comment by unilock** [comment] 2024-01-31 23:01
The config class I'm trying to use doesn't have a `boolean` field, actually - it's just a single `String` field.

You can see it here: https://github.com/unilock/ServerChatHeads/commit/ba0aaa34632c89f7814949b75a05011d6c850793

**Comment by sisby-folk** [comment] 2024-01-31 23:05
Reproduced, must be an upstream issue so i'll report it there

**Comment by sisby-folk** [comment] 2024-03-25 21:11
Looks like this has been fixed on their end with the swap to ban `final` instead of require it - we'll bump soon and verify it works

**Closed** 2024-04-06 04:56 UTC
